## Ndarray

In [2]:
import numpy as np

#1D array
arr1 = np.array([1,2,3,4,5])
print(type(arr1))
print(arr1.ndim)

#2D array
arr2 = np.array([[1,2,3],[4,5,6]])
print(type(arr2))
print(arr2.ndim)


# 3d array

arr3 = np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]]]
               )
print(type(arr3))
print(arr3.ndim)


<class 'numpy.ndarray'>
1
<class 'numpy.ndarray'>
2
<class 'numpy.ndarray'>
3


## Array attibutes

In [3]:
#dimention
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

#data type

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)



1
2
3
(5,)
(2, 3)
(2, 2, 3)
int64
int64
int64


In [4]:
arr1 = np.array([1,2,3,4,5])

print(arr1.dtype)


arr2 = np.array([1.2,2.2,3.3,4.3])

print(arr2.dtype)

int64
float64


In [5]:
arr2 = np.array([1.2,2,3,4])

print(arr2.dtype)

float64


In [6]:
arr2 = np.array([1.2,2,3,4,'5'])

print(arr2.dtype)

<U32


### selecting a data type for an array

In [7]:
arr = np.array([1,2,3],dtype = np.int8)
print(arr.dtype)

arr1 = np.array([1,2,300])
print(arr1.dtype)
arr2 = arr1.astype(np.int16)
print(arr2.dtype)


               

int8
int64
int16


### ndarray creation from existing data

In [8]:
#list

lst = [10,20,30,40,40.5]

arr = np.array(lst)

print(arr)

print(type(arr))
print(arr.dtype)



matrix = np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]]])

arr = np.array(matrix)

print(arr)

print(type(arr))
print(arr.dtype)
              

[10.  20.  30.  40.  40.5]
<class 'numpy.ndarray'>
float64
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
int64


In [9]:
#tuple

tpl = (10,20,30)

arr = np.array(tpl)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

<class 'numpy.ndarray'>
int64
(3,)
1


In [10]:
# dictionary

dc={'a':10,'b':20,'c':30}

keys = dc.keys()
values = dc.values()
items = dc.items()
# print(items)

arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [11]:
#item to ndarray

arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


In [12]:
np.random.uniform(1,10,(3,3))

array([[6.80298048, 8.6195731 , 7.66640679],
       [5.64310705, 7.38279888, 3.39662972],
       [7.66625144, 7.25468838, 7.67164343]])

In [13]:
arr = np.random.randint(1,10,(2,3))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[7 4 5]
 [9 4 9]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
6


In [14]:
arr = np.random.randint(1,10,(10,10))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[5 2 8 4 9 9 1 1 3 7]
 [5 4 1 5 9 7 3 8 8 7]
 [8 2 6 7 1 9 7 6 3 1]
 [6 5 3 1 1 5 4 2 6 2]
 [4 7 3 1 1 2 4 1 6 2]
 [1 9 1 1 9 5 8 6 9 1]
 [5 6 7 9 2 8 6 6 2 4]
 [7 2 7 2 3 9 1 6 3 7]
 [7 4 7 5 9 8 3 8 4 8]
 [4 2 9 8 1 6 6 9 4 1]]
<class 'numpy.ndarray'>
int32
(10, 10)
2
100


## array creation with range functions

In [15]:
# np.arange(first,end,step)

arr = np.arange(1,10,1).reshape(3,3)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2
9


In [16]:
# np.linspace(start,end(included),koita)


arr = np.linspace(1,10,10)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>
float64
(10,)
1
10


In [17]:
# np.logspace(start,end(included),koita)

arr = np.logspace(1,4,5)

print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

[   10.            56.23413252   316.22776602  1778.27941004
 10000.        ]


## List & indexing

In [18]:
#indexing 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])

print(arr1)
print(arr2)



print(arr1[2])
print(arr2[0][1])


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
3
2


In [19]:
# slicing

#1d = arr[start:end:step]

arr1_mod = arr1[1:4]

print(arr1_mod)



[2 3 4]


In [20]:
#1d = arr[row_start:row_end:step,column_start:column_end:step]
print(arr2)
#getting a row

row_0 = arr2[0:1,]
print(row_0)

#getting a column

col_0 = arr2[::,0:1]
print(col_0)

col_1= arr2[::,0:2]
print(col_1)


[[1 2 3]
 [4 5 6]]
[[1 2 3]]
[[1]
 [4]]
[[1 2]
 [4 5]]


In [ ]:
arr1_mod = arr1[1:4]
arr1_mod[0] = 100
print(arr1)
print(arr1_mod)


In [24]:
## Advance Indexing and iteration
list = np.array([10,20,30,40])

values = list[[2,3]]

print(values)



[30 40]


In [28]:
print(arr2)

print(arr2[[0,1],[1,2]])

print(arr2[arr2>2])

[[1 2 3]
 [4 5 6]]
[2 6]
[3 4 5 6]


In [29]:
arr = np.array([[10,20,30],[100,200,300]])

for i in np.nditer(arr):
    print(i)

10
20
30
100
200
300
