## Numpy Array Manipulation

In [2]:
import numpy as np

arr = np.random.randint(1,100,size=(10,5))

In [3]:
arr.shape

(10, 5)

In [4]:
b = arr.reshape(5,10)

b.shape

(5, 10)

In [5]:
flatten = b.flatten()

print(flatten.ndim)
flatten
column_wise_flattening = np.ravel(b,order = 'F')

print(column_wise_flattening)

1
[12 43 85 58 34 48 52 18  6 75 70 29 96 75 78 66 28 62 35 68 22 32 50 18
 65 64 22 73 77 88 53 80 50 23 94 56 61  8  7 64 85 83 19 74 42 75 32 38
  9 10]


In [6]:
a = np.random.randint(1,10,size = (2,3))
b = np.random.randint(20,30,size = (2,3))

print(a)
print(b)

[[8 9 8]
 [3 3 1]]
[[25 23 22]
 [23 26 28]]


## concatenate

In [7]:
con_row = np.concatenate((a,b),axis = 0)# row wise

print(con_row)

con_col = np.concatenate((a,b),axis = 1)# col wise

print(con_col)

[[ 8  9  8]
 [ 3  3  1]
 [25 23 22]
 [23 26 28]]
[[ 8  9  8 25 23 22]
 [ 3  3  1 23 26 28]]


In [8]:
x = np.random.randint(1,10,size = (2,3))
y = np.random.randint(20,30,size = (1,3))

con_row = np.concatenate((x,y),axis = 0)# row wise

print(con_row)

[[ 3  7  9]
 [ 4  5  1]
 [25 22 26]]


In [9]:
# transpose
mat= np.array([[10,20,30],[30,40,50]])


transpose = mat.T

print(transpose)


[[10 30]
 [20 40]
 [30 50]]


In [10]:
# array split

a = np.random.randint(1,10,size = (10,))
print(a)

splitted_array = np.array_split(a,3)

print(splitted_array)



[2 3 8 9 3 2 4 2 1 1]
[array([2, 3, 8, 9], dtype=int32), array([3, 2, 4], dtype=int32), array([2, 1, 1], dtype=int32)]


## arithmetic oparator mathematical function

In [11]:
x = np.array([10,20,30,40])
y = np.array([2,3,4,5])

add = np.add(x,y)
print(add)

sub = x-y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

remainder = x%y
print(remainder)

[12 23 34 45]
[ 8 17 26 35]
[ 20  60 120 200]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


In [12]:
# mathematical function

# trigonometry
# sin cos tan take values in radian
sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]


In [13]:
# log
x = np.array([10,8,16,40])
base_10_log_val = np.log10(x)
print(base_10_log_val)

two_diya_bhag = np.log2(x)
print(two_diya_bhag)

sqrt = np.sqrt(x)

print(sqrt)

[1.         0.90308999 1.20411998 1.60205999]
[3.32192809 3.         4.         5.32192809]
[3.16227766 2.82842712 4.         6.32455532]


## Comparison

In [14]:
x = np.array([10,20,30,40])
y = np.array([2,3,4,5])


greater_than = x>y
print(greater_than)

equal = x==y
print(equal)

#all () -> shob true kina
# any ()-> jekono akta true kina

print(np.all(greater_than))
print(np.all(equal))

[ True  True  True  True]
[False False False False]
True
False


In [16]:
x = np.array([10,8,16,40])

z = x.copy()

print(z)

z.sort()

print(z)

[10  8 16 40]
[ 8 10 16 40]


In [17]:
print(x)
sort_arr = np.sort(x)

print(sort_arr)
print(x)


[10  8 16 40]
[ 8 10 16 40]
[10  8 16 40]


In [19]:
# 2d array sorting
mat= np.array([[10,3,5],[8,4,9]])

hor_sort = np.sort(mat,axis=1)

print(hor_sort)

vert_sort = np.sort(mat,axis = 0)
print(vert_sort)


[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


## Searching




In [20]:
print(x)

[10  8 16 40]


In [24]:
# np.where

index = np.where(x==16)

print(index)

index = np.where(x>8,x,0)

print(index)

(array([2]),)
[10  0 16 40]


In [27]:
mat= np.array([[10,3,5],[8,4,9]])

index = np.where(mat>8)

print(index)

arr = np.where(mat>8,mat,0)

print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [30]:
maximum_value_index = np.argmax(x)
print(maximum_value_index)

minimum_value_index = np.argmin(x)
print(minimum_value_index)

3
1


## Counting

In [31]:
a = np.random.randint(1,100,size = (100,))
print(a)

[33 62 87 91 92 45 39 57 20 10 82 51  5 72 98 21 49 19 77 57 65 31 49 55
 67 24  2 72 88 30 26  2 26 97 91 93 71 28  7 89 21 66 47 63 68 17 49 46
 78 12 63 82 68 21 97 52 58 43 99 31 44 93 74 15 55 23 49 33 30 63 46 22
 99 31 23 78 18 80 15  3 41  2 41 55 83 76 54  7 79 95 97 96 28 13 66 12
 47 73 15 14]


In [35]:
value_greater_then_60 = np.count_nonzero(a>10)
print(value_greater_then_60)

value_equal = np.count_nonzero(a==40)
print(value_equal)

92
0


In [39]:
unique_value,count = np.unique(a,return_counts = True)
print(unique_value)

print(count)

[ 2  3  5  7 10 12 13 14 15 17 18 19 20 21 22 23 24 26 28 30 31 33 39 41
 43 44 45 46 47 49 51 52 54 55 57 58 62 63 65 66 67 68 71 72 73 74 76 77
 78 79 80 82 83 87 88 89 91 92 93 95 96 97 98 99]
[3 1 1 2 1 2 1 1 3 1 1 1 1 3 1 2 1 2 2 2 3 2 1 2 1 1 1 2 2 4 1 1 1 3 2 1 1
 3 1 2 1 2 1 2 1 1 1 1 2 1 1 2 1 1 1 1 2 1 2 1 1 3 1 2]


# statistical function

In [42]:
data = np.genfromtxt('student_scores.csv',delimiter =',',skip_header=1)
print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [51]:
math_mark = data[::,:1]
print(math_mark.T)

max_math_mark = np.max(math_mark)
print(max_math_mark)

min_math_mark = np.min(math_mark)
print(min_math_mark)

avg_math_mark = np.mean(math_mark)
print(avg_math_mark)

median_math_mark = np.median(math_mark)
print(median_math_mark)

std_math_mark  =np.std(math_mark)
print(std_math_mark)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


In [52]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


## linear Algebra


In [59]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

#dot 

dot_product = np.dot(A,B)

print(dot_product)

# trace 

print(np.trace(B))




[[ 58  64]
 [139 154]]
17


In [62]:
sq_mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

det_of_sq = np.linalg.det(sq_mat)
print(det_of_sq)

rank_sq = np.linalg.matrix_rank(sq_mat)
print(rank_sq)

6.66133814775094e-16
2


In [65]:
 A = np.array([[1, 2], [3, 4]])
 B = np.array([[5, 6], [7, 8]])

print(A*B)

[[ 5 12]
 [21 32]]
